name: Tests

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: 	uv sync --no-dev --frozen

      - name: Run tests
        run: uv run pytest tests/ -v --tb=short

      - name: Install Xvfb and GL libs (Linux Python 3.11 only)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        env:
          DISPLAY: ':99.0'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb x11-utils libxkbcommon-x11-0 libgl1 libglu1-mesa mesa-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Smoke test game.py (Linux Python 3.11 only)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        env:
          DISPLAY: ':99.0'
          LIBGL_ALWAYS_SOFTWARE: '1'
        run: |
          echo "Running game.py for 5s"
          set +e
          timeout 5s uv run python game.py
          rc=$?
          set -e
          if [ $rc -eq 124 ]; then
            echo "OK: game.py ran and timed out after 5s as expected"
          elif [ $rc -eq 0 ]; then
            echo "OK: game.py exited cleanly within 5s"
          else
            echo "FAIL: game.py exited with $rc"
            exit $rc
          fi

      - name: Run tests with coverage (Linux Python 3.11 only)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        env:
          DISPLAY: ':99.0'
          LIBGL_ALWAYS_SOFTWARE: '1'
        run: uv run pytest tests/ --cov=src/laser_gates --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov (Linux Python 3.11 only)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
